apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bankapp-pvc
  namespace: bankapp
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
